version: '3.3'

services:
  rest-api:
    build:
      context: .
      dockerfile: rest.Dockerfile
    container_name: rest-api
    command: bash -c "uvicorn rest.main:app --host 0.0.0.0 --port 8888 --reload"
    ports:
      - "8888:8888"

